name: .NET Core Desktop

on:
  push:
    branches:
      - master
    tags:
      - v**
  pull_request:
    branches:
      - master
    tags:
      - v**

jobs:

  build:

    runs-on: windows-latest
    
    env:
      Solution_Name: Versatile.sln
      Project_Name: Versatile
      Output_Folder: .output
      Release_Folder: .release

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-prerelease: true


    - name: Restore the application
      run: msbuild ${{ env.Project_Name }} /t:Restore /p:Configuration=release
        
    - name: Build
      run: msbuild ${{ env.Project_Name }} /p:Configuration=release /p:OutputPath=.\${{ env.Output_Folder }}


    - run: |
        echo "App_Version=${{ github.ref }}" >> $env:GITHUB_ENV

    - run: |
        mkdir ${{ env.Release_Folder }}

    - name: Archive Build
      run: |
        Compress-Archive .\${{ env.Output_Folder }}\* .\${{ env.Release_Folder }}\${{ env.Project_Name }}-v${{ env.App_Version }}.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ env.Project_Name }}-v${{ env.App_Version }}
        tag_name: v${{ env.App_Version }}
        files: |
          ${{ env.Release_Folder }}/Versatile-v${{env.App_Version}}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
