name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest
    env:
      Solution_Name: Versatile.sln
      Project_Name: Versatile
      OUT_DIR: .\.release

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-prerelease: true


    - name: Get version
      uses: naminodarie/get-net-sdk-project-versions-action@v1.1.2
      id: get_version
      with:
        proj-path: ./${{ env.Project_Name }}/${{ env.Project_Name }}.csproj
        
    - run: |
        echo "APP_VERSION=${{steps.get_version.outputs.assembly-version}}" >> $env:GITHUB_ENV

    - run: |
        mkdir ${{ env.OUT_DIR }}
        
    - name: Archive Build
      run: |
        Compress-Archive .\Versatile\* -DestinationPath ${{ env.OUT_DIR }}\Versatile-v${{env.APP_VERSION}}.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: Versatile-v${{ env.APP_VERSION }}
        tag_name: v${{ env.APP_VERSION }}
        files: |
          ${{ env.OUT_DIR }}\Versatile-v${{env.APP_VERSION}}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
